// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: hsb_indicator

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TestLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestLabel, "Display Test Label");
    lv_obj_set_style_text_font(ui_TestLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

}
