#!/bin/bash
#Assign existing hostname to $hostn
hostn=$(cat /etc/hostname)
newhost=`cat /sys/class/net/eth0/address`
newhost=`echo ${newhost//:}`

#Display existing hostname
echo "Existing hostname is $hostn"

#display new hostname
echo "Your new hostname is $newhost"

if [ "$hostn" == "$newhost" ]; then
  exit 0
fi

#change hostname in /etc/hosts & /etc/hostname
sed -i "s/$hostn/$newhost/g" /etc/hosts
sed -i "s/$hostn/$newhost/g" /etc/hostname

#Press a key to reboot
reboot


