#!/bin/bash

cd "$(dirname "$0")"

export LD_LIBRARY_PATH=/home/mlanner/Development/wolf/libs
export QT_QPA_PLATFORM=linuxfb:fb=/dev/fb1:size=320x240
export QT_QPA_EVDEV_TOUCHSCREEN_PARAMETERS=/dev/input/event0:rotate=270

./mold -c test.cfg $@

