#!/bin/bash
 
set -e
 
curl http://www.probeview.com/update/0_11_3.tar.xz -o update.tar.xz
tar -xf update.tar.xz
echo "done unpacking"
 
 
pkill -c -n mold
echo "done killing"
 
bash -c "sleep 10;pkill -c -9 mold;./exec-mold"&


