#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $SCRIPT_DIR/log_environment

while read line
do
  PRIORITY=$(echo "$line" | awk -f $SCRIPT_DIR/get_priority.awk)
  if [ -z "$PRIORITY" ]
  then
    PRIORITY=$LOG_DEFAULT_PRIORITY
  fi
  echo $line | systemd-cat -p $PRIORITY -t $LOG_IDENTIFIER
done < "${1:-/dev/stdin}"
