#!/bin/bash

# This should be run at regular intervals (i.e. every hour)
# Tries to upload files from the upload directory if gsm is not enabled

if [ ! -f "/root/gsm_enabled" ]
then
echo "not a gsm image, upload logs"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $SCRIPT_DIR/log_environment

cd $LOG_UPLOAD_DIR
# upload newest files first, because these are the ones we're most interested in
FILES=$(find . -mindepth 1 -maxdepth 1 -printf "%T@ %p\n" | sort -rn | awk '{ print $2 }' | cut -c 3-)
for f in $FILES
do
    $SCRIPT_DIR/upload_log $f
done
fi
