#!/bin/bash

set -e

cd "$(dirname "$0")"

if [ ! -e /dev/loop0 ]; then
  mknod -m660 /dev/loop0 b 7 8
fi

cd ..

./build/make_build
./build/install
mv ../install .
find install

cat ../build/mold/version.cpp
