#!/bin/bash

set -e

script_dir="$(realpath "$(dirname "$0")")"
src_dir=`pwd`
images_dir=$src_dir/images/

mkdir -p /opt/base_image/ /opt/build/

if [ ! -e /dev/loop0 ]; then
  mknod -m660 /dev/loop0 b 7 8
fi

echo "creating base image"
cd /opt/base_image/
$script_dir/../build/get_dependencies.d --image --imageResultName base.img || exit 1
mount -o loop,offset=272629760 /opt/base_image/base.img /mnt

cd $src_dir

rm -frv /mnt/opt/mold
mkdir -p /mnt/opt/mold || exit 1
cp -rv install/* /mnt/opt/mold/ || exit 1
cp -rv $src_dir/image/* /mnt/ || exit 1
ffmpeg -vcodec png -i $src_dir/screen_images/registering_device.png -vcodec rawvideo -f rawvideo -pix_fmt rgb565 /mnt/root/registering_device.raw || exit 1
echo 'name_servers=8.8.4.4' >> /mnt/etc/resolvconf.conf || exit 1

# umount
umount /mnt

gsm_enabled="$1"
gsm_confirmation_required="$2"
config="$3"
echo "gsm_enabled: $gsm_enabled"
echo "gsm_confirmation_required: $gsm_confirmation_required"
echo "config: $config"

mount -o loop,offset=272629760 /opt/base_image/base.img /mnt || exit 1

ffmpeg -vcodec png -i $src_dir/screen_images/splash_${config}.png -vcodec rawvideo -f rawvideo -pix_fmt rgb565 /mnt/root/splash.raw || exit 1

cp -v $src_dir/ci/$config.cfg /mnt/opt/mold/gui.cfg || exit 1
cp -v $src_dir/ci/register_${config} /mnt/root/register || exit 1

if [ "$gsm_enabled" = true ]
then
  touch /mnt/root/gsm_enabled || exit 1
fi

if [ "$gsm_confirmation_required" = true ]
then
  touch /mnt/root/gsm_confirmation_required || exit 1
fi

umount /mnt

# compress
echo "compressing image"
cd /opt/base_image/
# pixz -k base.img
pigz -k base.img

# rename
OFFSET=$(cat $script_dir/../version.txt|  grep offset |cut -d = -f2)
RESULT_NAME="${CI_BUILD_REF_NAME//'/'/'-'}"
RESULT_NAME+="-"
PIPELINE=$(($CI_PIPELINE_IID-$OFFSET))
RESULT_NAME+="$PIPELINE"
RESULT_NAME+="_"
RESULT_NAME+=$config

if [ "$gsm_enabled" = true ]
then
  RESULT_NAME+="_gsm"
fi

RESULT_NAME+="_deploy"
RESULT_NAME+=".img.gz"
echo "image file name: $RESULT_NAME"

mv base.img.gz $RESULT_NAME
mkdir -p $images_dir
cp $RESULT_NAME $images_dir
