#!/bin/bash

set -e

script_dir="$(realpath "$(dirname "$0")")"
src_dir=`pwd`

$script_dir/exec_create_image $@

for filename in $src_dir/images/*.img.gz; do
  # upload
  echo "uploading $filename"
  time sshpass -p $UPLOAD_SERVER_PASSWORD scp -o StrictHostKeyChecking=no $filename $UPLOAD_SERVER
  rm -v $filename
done
