#!/bin/bash

device_id=$(cat /etc/hostname)
secret=$(< /dev/urandom tr -cd '[:alnum:]' | head -c 32;echo;)

echo "device_id: $device_id"
echo "secret: $secret"

echo "$secret" > /root/secret

dd if=registering_device.raw of=/dev/fb1

while true
do
   curl --silent --show-error --fail -d "" -X POST "https://testcloud.umidus.com:4432/whitelist?boxId=${device_id}&secret=${secret}" && break
   sleep 5
done

# delete script
rm -- "$0"
sync
reboot
