#!/bin/bash

script_dir="$(dirname "$(readlink -f "$0")")"

work_dir=`mktemp -d`
cd $work_dir

# dependencies
base_image='base.img'
$script_dir/../../build/get_dependencies.d --image --imageResultName $base_image || exit 1
curl -LO https://raw.githubusercontent.com/dhruvvyas90/qemu-rpi-kernel/master/kernel-qemu-4.4.34-jessie

# copy testing binaries
cp -r $script_dir/../../install .

# ssh key
rm -v ./ssh_key_ci*
ssh-keygen -f ./ssh_key_ci -N '' || exit 1

$script_dir/run_qemu &
$script_dir/run_tests
test_return_code=$?
echo "tests ended with result code:$test_return_code"
pkill qemu-system-arm
rm -r $work_dir
exit $test_return_code
