#!/bin/bash

ssh_host=root@localhost
ssh_port=5022

# Start trying and retrying
((count = 30))
while [[ $count -ne 0 ]] ; do
    ssh $ssh_host -o StrictHostKeyChecking=no -4 -i ./ssh_key_ci -p $ssh_port true
    rc=$?
    if [[ $rc -eq 0 ]] ; then
        ((count = 1))
        echo 'successfully tested ssh connection'
    else
      sleep 2
    fi
    ((count = count - 1))
done

# Print a message if we failed
if [[ $rc -ne 0 ]] ; then
    echo "Could not connect to $* after 30 attempts - stopping."
    exit 1
fi

set -ex

echo 'connecting and running tests'
ssh $ssh_host -o StrictHostKeyChecking=no -4 -i ./ssh_key_ci -p $ssh_port <<ENDSSH
set -ex
cd /opt/install
source enviroment
./bin/tests_gtest
ENDSSH

