#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export LOG_TEMP_DIR=/var/log/unittest/temp
export LOG_PERSISTENT_DIR=/var/log/unittest/persistent

TMP=unittest_$RANDOM


source $SCRIPT_DIR/../logger
(export LOG_IDENTIFIER=$TMP; $SCRIPT_DIR/stderr_tester 2> >(log_error) | log_debug)

CHECK=$(journalctl -t $TMP -n 1 -p debug..debug -q | grep "This goes to stdout")
if [ -z "$CHECK" ]
then
    echo test_stderr_redirection Could not find normal log entry $CHECK
    exit 1
fi

CHECK=$(journalctl -t $TMP -n 1 -p err..err -q | grep "This goes to stderr")
if [ -z "$CHECK" ]
then
    echo test_stderr_redirection Could not find normal log entry $CHECK
    exit 1
fi

echo "test_stderr_redirection executed successfully"
