/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p org_desktop_networkmanager -N -i array_of_string_variant.hpp -i connection.hpp -i array_of_string_uint32.hpp -i array_of_string_string.hpp org.freedesktop.NetworkManager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "org_desktop_networkmanager.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerInterface
 */

OrgFreedesktopNetworkManagerInterface::OrgFreedesktopNetworkManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerInterface::~OrgFreedesktopNetworkManagerInterface()
{
}

