/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p org_desktop_networkmanager_device -N -i array_of_string_variant.hpp org.freedesktop.NetworkManager.Device.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "org_desktop_networkmanager_device.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerDeviceInterface
 */

OrgFreedesktopNetworkManagerDeviceInterface::OrgFreedesktopNetworkManagerDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerDeviceInterface::~OrgFreedesktopNetworkManagerDeviceInterface()
{
}

