#!/bin/bash

cd "$(dirname "$0")"
source enviroment

WAITTIME=3

date
until ./bin/gsm_mux --device /dev/ttyAMA0 $@; do
  RESULT=$?
  echo "gsm_mux stopped with code $RESULT. Restarting in $WAITTIME second."
  ./scripts/logging/save_crash_logs $RESULT
  date
  sleep $WAITTIME
done

./scripts/logging/save_crash_logs 0
