#!/bin/bash

echo "starting rename: $(date)"
# Assign existing hostname to $hostn
hostn=$(cat /etc/hostname)
newhost=`grep -Po '^Serial\s*:\s*\K[[:xdigit:]]{16}' /proc/cpuinfo | cut -c5-`

#display new hostname
echo "Your old hostname is $hostn"
echo "Your new hostname is $newhost"

if [ "$hostn" == "$newhost" ]; then
  echo "skipping rename because device is alread called '$newhost'"
  exit 1
fi

# raspi-config --expand-rootfs
echo "renaming device to $newhost"

#change hostname in /etc/hosts & /etc/hostname
sed -i "s/$hostn/$newhost/g" /etc/hosts
sed -i "s/$hostn/$newhost/g" /etc/hostname

/sbin/reboot

exit 0
