#!/bin/bash

# turn of rpi leds
echo none > /sys/class/leds/led0/trigger
echo none > /sys/class/leds/led1/trigger
source /opt/mold/scripts/logging/logger

# mold
(export LOG_IDENTIFIER=mold.main; \
 /opt/mold/exec-mold -c gui.cfg 2> >(log_error) | log;
   exit ${PIPESTATUS[0]})
